# Autogenerated wrapper script for SurfelsLib_jll for x86_64-linux-gnu-cxx11
export libsurfels

using GLEW_jll
using GLU_jll
JLLWrappers.@generate_wrapper_header("SurfelsLib")
JLLWrappers.@declare_library_product(libsurfels, "libsurfels.so")
function __init__()
    JLLWrappers.@generate_init_header(GLEW_jll, GLU_jll)
    JLLWrappers.@init_library_product(
        libsurfels,
        "lib/libsurfels.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
